CREATE DATABASE IF NOT EXISTS SNAPFLASH_DATABASE;

USE SNAPFLASH_DATABASE;

CREATE TABLE IF NOT EXISTS Users (
    userId UUID PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    userName VARCHAR NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- INSERT INTO Users 

CREATE TABLE IF NOT EXISTS Decks(
    deckId UUID PRIMARY KEY,
    -- userId UUID,
    deckName VARCHAR NOT NULL,
    description TEXT,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ScanHistory(
    historyId UUID PRIMARY KEY,
    userId UUID,
    imageURL TEXT,
    extractedText TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS FlashCards(
    flashcardId UUID PRIMARY KEY,
    deckId UUID,
    word VARCHAR NOT NULL,
    translation TEXT NOT NULL,
    definition TEXT NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (deckId) REFERENCES Decks(deckId) ON DELETE CASCADE
);


