spring.datasource.url=jdbc:postgresql://ep-restless-sunset-a1bciox8-pooler.ap-southeast-1.aws.neon.tech/snapflash_database?&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Srh5YCX2wAfK

spring.flyway.url=jdbc:postgresql://ep-restless-sunset-a1bciox8-pooler.ap-southeast-1.aws.neon.tech/snapflash_database?&sslmode=require&channelBinding=require
spring.flyway.user=neondb_owner
spring.flyway.password=npg_Srh5YCX2wAfK